version: '3.8'

services:
  # app:
  #   build: ./
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql
  #     - backend
    
  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # backend:
  #   build: ./src/backend/
  #   ports:
  #     - "8800:8800"
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./src/backend:/backend
  #   working_dir: /src/backend

volumes:
  mysql-data: