version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "9000:5173"
  #   depends_on:
  #     - backend
    
  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./backend/src/database/sql.sql:/docker-entrypoint-initdb.d/sql.sql

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3030:3030"
  #   depends_on:
  #     - mysql
